services:
  frontend:
    profiles: ["production"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./certbot/www/:/var/www/certbot # read challenge files from certbot
      - ./certbot/conf/:/etc/letsencrypt # read actual certs
      # TODO: nginx log volume?
      # TODO: configure this if I need to develop live on the Docker instance
      #   - /app/node_modules
      #   - ./frontend:/app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    environment:
      - SERVER_NAME=$SERVER_NAME
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY=$SSL_CERTIFICATE_KEY
    entrypoint: ["/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]

  api-server:
    platform: linux/x86_64
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server
    restart: unless-stopped
    environment:
      DB_POST: db
      DB_NAME: aldrig-dev
      DB_USERNAME: ingen
      DB_PASSWORD: vilket ord som helst duger # "any word will do"
    volumes:
      - ./api-server/:/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: aldrig-dev
      POSTGRES_USER: ingen
      POSTGRES_PASSWORD: vilket ord som helst duger
    ports:
      - "5432:5432"

  graphql-server:
    profiles: ["original"]
    build:
      context: ./graphql-server
      dockerfile: Dockerfile
    container_name: graphql-server
    restart: unless-stopped
    environment:
      MONGODB_URI: $MONGODB_URI
    # ports:
    #   - "4000:4000"
    networks:
      - frontend
      - backend

  # LetsEncrypt certbot; certbot.eff.org
  certbot:
    # In this context, certbot can't configure nginx directly, so no point
    # running it as a service. Instead, while the frontend server is running,
    # run the certonly command to write the updated certificates:
    #
    # sudo docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d aldrig-ingenstans.site
    profiles: ["certbot"]
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot # write challenge files for nginx
      - ./certbot/conf/:/etc/letsencrypt # write actual certs

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  pgdata:
    driver: local
  nginxdata:
    driver: local
